# Generated by Django 6.1.1 on 2026-09-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='مثلاً «سال\u200cهای تجربه» یا «مشتری راضی»', max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='امتیاز از ۱ تا ۵ (اختیاری).', null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='restaurants/testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
