# Generated by Django 6.1.1 on 2026-09-13 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantstat_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='restaurants/hero/')),
                ('title', models.CharField(blank=True, help_text='عنوان بزرگ روی اسلاید؛ اگر خالی بماند، نام رستوران نمایش داده می\u200cشود.', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='زیرعنوان کوچک (مثلاً یک شعار کوتاه).', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
