# Generated by Django 6.1.1 on 2026-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این محصول در بخش «غذاهای پیشنهادی» بالای صفحه اصلی نمایش داده می\u200cشود.'),
        ),
    ]
